name: Fetch Debian Popcon Data on MariaDB

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper pull and rebase operations

      - name: Fetch Debian Popcon data for mariadb-server
        run: |
          curl -s "https://qa.debian.org/cgi-bin/popcon-data?packages=mariadb-server;from_date=2023-01-01;to_date=2025-03-01" | \
          jq '.["mariadb-server"] | to_entries | map(.key as $date | {month: ($date | split("-")[0] + "-" + split("-")[1]), count: (.value.no_files + .value.old + .value.recent)}) | group_by(.month) | map({(.[0].month): (map(.count) | add)}) | add' > debian_popcon.json

      - name: Commit and push if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          # Fetch the latest changes from the remote repository
          git fetch origin

          # Rebase local changes on top of the remote main branch
          git rebase origin/main

          # Stage the changes
          git add debian_popcon.json

          # Commit and push if there are changes
          git diff --staged --quiet || (git commit -m "Update Debian Popcon data" && git push origin main)
