name: Debian Popcon

on:
  schedule:
    - cron: '5 3 1 * *'
  workflow_dispatch:  # Allows manual triggering

# Add permissions block
permissions:
  contents: write

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper pull and rebase operations

      - name: Fetch Debian Popcon data for mariadb-server
        run: |
          # Calculate date range dynamically
          START_DATE="2023-01-01"
          END_DATE=$(date -I)
          
          curl -sf "https://qa.debian.org/cgi-bin/popcon-data?packages=mariadb-server;from_date=${START_DATE};to_date=${END_DATE}" > data/debian_popcon/raw.json

      - name: Install requirements
        run: |
          python -m pip install pandas

      - name: Process data
        run: |
          python data/debian_popcon/raw2monthly.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          timestamp=$(date -I)
          git commit -m "debian popcon ${timestamp}" || exit 0
          git push