name: Github New PRs External

on:
  schedule:
    - cron: '0 4 1 * *'  # Runs at 6 AM EET (4 AM UTC) on the first day of each month
  workflow_dispatch:  # Allows manual triggering

# Add permissions block
permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for proper pull and rebase operations

      - name: Install requirements
        run: |
          python -m pip install pandas

      - name: Fetch data
        run: |
          python data/github_new_prs_external/fetch.py

      - name: Process data
        run: |
          python data/github_new_prs_external/latest2monthly.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          timestamp=$(date -I)
          git commit -m "github new prs external ${timestamp}" || exit 0
          git push